import type { Address,Product,Quote } from './types';
const base=process.env.CORREIOS_API_BASE||'https://api.correios.com.br';
const cepPath=process.env.CORREIOS_CEP_PATH||'/cep/v1/enderecos';
const cep=(v:string)=>v.replace(/\D/g,'');
let cached:{token:string;expires:number}|null=null;
async function token(){if(cached&&cached.expires>Date.now()+60000)return cached.token;const {CORREIOS_USER, CORREIOS_API_PASSWORD,CORREIOS_POSTING_CARD}=process.env;if(!CORREIOS_USER||!CORREIOS_API_PASSWORD||!CORREIOS_POSTING_CARD)throw new Error('Correios não configurados');const res=await fetch(`${base}/token/v1/autentica/cartaopostagem`,{method:'POST',headers:{Authorization:'Basic '+Buffer.from(`${CORREIOS_USER}:${CORREIOS_API_PASSWORD}`).toString('base64'),'Content-Type':'application/json'},body:JSON.stringify({numero:CORREIOS_POSTING_CARD}),cache:'no-store'});if(!res.ok)throw new Error('Falha de autenticação nos Correios');const data=await res.json();if(!data.token)throw new Error('Token dos Correios ausente');cached={token:data.token,expires:new Date(data.expiraEm||Date.now()+30*60000).getTime()};return cached.token}
async function correiosGet(path:string,t:string){const res=await fetch(base+path,{headers:{Authorization:`Bearer ${t}`,Accept:'application/json'},cache:'no-store'});if(!res.ok)throw new Error(`Correios: ${res.status}`);return res.json()}
export async function validateAddress(address:Address){if(!/^\d{8}$/.test(cep(address.cep))||!address.street?.trim()||!address.number?.trim()||!address.recipient?.trim())throw new Error('Preencha CEP, rua, número e destinatário.');const t=await token();const data=await correiosGet(`${cepPath}/${cep(address.cep)}`,t);const city=String(data.localidade||data.cidade||'').trim();const state=String(data.uf||'').trim();if(!city||!state)throw new Error('CEP não confirmado pelos Correios.');const norm=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();if(norm(city)!==norm(address.city)||state.toUpperCase()!==address.state.trim().toUpperCase())throw new Error('Cidade ou UF não corresponde ao CEP informado.');const officialStreet=String(data.logradouro||'').trim();if(officialStreet&&norm(officialStreet)!==norm(address.street))throw new Error('Rua não corresponde ao CEP informado.');return {city,state,cep:cep(address.cep)} }
const brMoney=(value:string)=>Math.round(Number(value.replaceAll('.','').replace(',','.'))*100);
export async function quoteShipping(artisanCep:string,items:{product:Product;quantity:number}[],address:Address):Promise<Quote[]>{const dest=await validateAddress(address);if(dest.city.toLocaleLowerCase('pt-BR')==='xexéu'&&dest.state==='PE')return [{service:'local',label:'Entrega pela artesã em Xexéu',priceCents:0,days:null,kind:'local'}];if(!/^\d{8}$/.test(cep(artisanCep)))throw new Error('CEP de postagem da artesã não informado.');const t=await token();const weight=items.reduce((s,i)=>s+i.product.weight_g*i.quantity,0);const length=Math.max(...items.map(i=>i.product.length_cm));const width=Math.max(...items.map(i=>i.product.width_cm));const height=items.reduce((s,i)=>s+i.product.height_cm*i.quantity,0);const services=(process.env.CORREIOS_SERVICES||'').split(',').map(s=>s.split(':')).filter(s=>s.length===2);const quotes=await Promise.allSettled(services.map(async([code,label])=>{const q=new URLSearchParams({cepOrigem:cep(artisanCep),cepDestino:dest.cep,psObjeto:String(weight),tpObjeto:'2',comprimento:String(length),largura:String(width),altura:String(height)});if(process.env.CORREIOS_CONTRACT)q.set('nuContrato',process.env.CORREIOS_CONTRACT);if(process.env.CORREIOS_DR)q.set('nuDR',process.env.CORREIOS_DR);const [price,deadline]=await Promise.all([correiosGet(`/preco/v1/nacional/${code}?${q}`,t),correiosGet(`/prazo/v1/nacional/${code}?${new URLSearchParams({cepOrigem:cep(artisanCep),cepDestino:dest.cep})}`,t)]);const priceCents=brMoney(String(price.pcFinal||''));const days=Number(deadline.prazoEntrega);if(!Number.isFinite(priceCents)||priceCents<=0||!Number.isInteger(days)||days<0)throw new Error('Cotação inválida');return {service:code,label,priceCents,days,kind:'correios' as const}}));return quotes.filter(r=>r.status==='fulfilled').map(r=>(r as PromiseFulfilledResult<Quote>).value)}
