'use server';
import { revalidatePath } from 'next/cache';
import { redirect } from 'next/navigation';
import { adminDb,currentUser,serverDb } from '@/lib/supabase';
const val=(f:FormData,k:string)=>String(f.get(k)||'').trim();
const slug=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
async function requireUser(){const user=await currentUser();if(!user)throw new Error('Faça login.');return user}
async function requireAdmin(){const user=await requireUser();const {data}=await adminDb().from('profiles').select('role').eq('id',user.id).single();if(data?.role!=='admin')throw new Error('Acesso restrito.');return user}
async function ownArtisan(){const user=await requireUser();const {data}=await adminDb().from('artisans').select('*').eq('user_id',user.id).maybeSingle();if(!data)throw new Error('Cadastre seu perfil de artesã.');return data}
export async function signIn(form:FormData){const db=await serverDb();const {error}=await db.auth.signInWithPassword({email:val(form,'email'),password:val(form,'password')});if(error)redirect('/entrar?erro=credenciais');redirect('/painel')}
export async function signUp(form:FormData){const db=await serverDb();const {error}=await db.auth.signUp({email:val(form,'email'),password:val(form,'password')});if(error)redirect('/cadastro?erro=cadastro');redirect('/entrar?novo=1')}
export async function signOut(){const db=await serverDb();await db.auth.signOut();redirect('/')}
export async function saveArtisan(form:FormData){const user=await requireUser();const db=adminDb();const {data:existing}=await db.from('artisans').select('*').eq('user_id',user.id).maybeSingle();const name=val(form,'name');if(name.length<2)throw new Error('Informe o nome.');const input={name,story:val(form,'story'),techniques:val(form,'techniques'),posting_cep:val(form,'posting_cep').replace(/\D/g,''),slug:existing?.slug||`${slug(name)}-${user.id.slice(0,6)}`,status:'pending',featured_month:null};if(!/^\d{8}$/.test(input.posting_cep))throw new Error('CEP de postagem inválido.');const {error}=existing?await db.from('artisans').update(input).eq('id',existing.id):await db.from('artisans').insert({...input,user_id:user.id});if(error)throw error;revalidatePath('/painel');redirect('/painel')}
export async function saveProduct(form:FormData){const artisan=await ownArtisan();const db=adminDb();const id=val(form,'id');if(id){const {data:old}=await db.from('products').select('artisan_id,slug').eq('id',id).single();if(old?.artisan_id!==artisan.id)throw new Error('Peça não pertence à sua conta.')}const name=val(form,'name');const category=val(form,'category');const price_cents=Math.round(Number(val(form,'price').replace(',','.'))*100);const stock=Number(val(form,'stock'));const weight_g=Number(val(form,'weight_g'));const length_cm=Number(val(form,'length_cm'));const width_cm=Number(val(form,'width_cm'));const height_cm=Number(val(form,'height_cm'));if(!name||!category||!Number.isInteger(price_cents)||price_cents<1||!Number.isInteger(stock)||stock<0||[weight_g,length_cm,width_cm,height_cm].some(n=>!Number.isFinite(n)||n<=0))throw new Error('Confira os dados da peça.');const input={artisan_id:artisan.id,name,slug:id?(await db.from('products').select('slug').eq('id',id).single()).data?.slug:`${slug(name)}-${crypto.randomUUID().slice(0,6)}`,description:val(form,'description'),category,price_cents,stock,weight_g,length_cm,width_cm,height_cm,status:'pending'};const {error}=id?await db.from('products').update(input).eq('id',id):await db.from('products').insert(input);if(error)throw error;revalidatePath('/painel');redirect('/painel')}
export async function uploadImage(form:FormData){const artisan=await ownArtisan();const kind=val(form,'kind');const productId=val(form,'productId');if(kind==='product'){const {data}=await adminDb().from('products').select('artisan_id').eq('id',productId).single();if(data?.artisan_id!==artisan.id)throw new Error('Peça não pertence à sua conta.')}const file=form.get('image');if(!(file instanceof File)||file.size>5*1024*1024||!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('Envie JPG, PNG ou WebP até 5 MB.');const ext=file.type.split('/')[1].replace('jpeg','jpg');const path=`${artisan.id}/${crypto.randomUUID()}.${ext}`;const db=adminDb();const {error}=await db.storage.from('catalog').upload(path,file,{contentType:file.type,upsert:false});if(error)throw error;if(kind==='profile')await db.from('artisans').update({photo_path:path,status:'pending'}).eq('id',artisan.id);else {await db.from('product_images').insert({product_id:productId,path});await db.from('products').update({status:'pending'}).eq('id',productId)}revalidatePath('/painel');redirect('/painel')}
export async function moderate(form:FormData){await requireAdmin();const table=val(form,'table');const id=val(form,'id');const status=val(form,'status');if(!['artisans','products'].includes(table)||!['approved','rejected'].includes(status))throw new Error('Ação inválida.');const {error}=await adminDb().from(table).update({status}).eq('id',id);if(error)throw error;revalidatePath('/painel');redirect('/painel')}
export async function featureArtisan(form:FormData){await requireAdmin();const id=val(form,'id');const month=val(form,'month');if(!/^\d{4}-\d{2}$/.test(month))throw new Error('Mês inválido.');const db=adminDb();const {data}=await db.from('artisans').select('status').eq('id',id).single();if(data?.status!=='approved')throw new Error('Aprove a artesã antes.');await db.from('artisans').update({featured_month:null}).eq('featured_month',month+'-01');const {error}=await db.from('artisans').update({featured_month:month+'-01'}).eq('id',id);if(error)throw error;revalidatePath('/');redirect('/painel')}
export async function changeOrder(form:FormData){const user=await requireUser();const id=val(form,'id');const status=val(form,'status');const tracking=val(form,'tracking_code');const db=adminDb();const {data:order}=await db.from('orders').select('*,artisans(user_id)').eq('id',id).single();if(!order)throw new Error('Pedido não encontrado.');const {data:profile}=await db.from('profiles').select('role').eq('id',user.id).maybeSingle();const isAdmin=profile?.role==='admin';if(!isAdmin&&(order.artisans as {user_id:string})?.user_id!==user.id)throw new Error('Acesso restrito.');const allowed:Record<string,string[]>={paid:['in_preparation'],in_preparation:order.delivery_kind==='local'?['out_for_delivery']:['posted'],posted:['delivered'],out_for_delivery:['delivered'],delivered:['completed']};if(!isAdmin&&!allowed[order.status]?.includes(status))throw new Error('Transição de estado inválida.');if(status==='posted'&&!tracking)throw new Error('Informe o código de rastreamento.');const {error}=await db.from('orders').update({status,tracking_code:status==='posted'?tracking:order.tracking_code}).eq('id',id);if(error)throw error;revalidatePath('/painel');redirect('/painel')}
export async function sendSupport(form:FormData){if(val(form,'website'))redirect('/contato?enviado=1');const name=val(form,'name'),email=val(form,'email'),message=val(form,'message');if(name.length<2||name.length>100||!/^\S+@\S+\.\S+$/.test(email)||email.length>200||message.length<10||message.length>2000)throw new Error('Confira a mensagem e o e-mail.');const {error}=await adminDb().from('support_requests').insert({name,email,message});if(error)throw error;redirect('/contato?enviado=1')}
